#!/bin/sh
set -eo pipefail

echo "[LAMBDA FLAME] Starting custom runtime..."

if [ -z "$NODE_RUNTIME_PATH" ];
then
    export NODE_RUNTIME_PATH=nodejs/node
fi

export LAMBDA_FLAME_OUTPUT=lambda-flame-output

mkdir /tmp/"$LAMBDA_FLAME_OUTPUT"

collect() {
    $NODE_RUNTIME_PATH --prof-process --preprocess -j /tmp/"$LAMBDA_FLAME_OUTPUT"/isolate*.log >> /tmp/"$LAMBDA_FLAME_OUTPUT"/isolate-output.json
    $NODE_RUNTIME_PATH nodejs/Collector.js
}

export NODE_PATH=/var/task/node_modules:/var/node_modules:/node_modules:/nodejs/node_modules:/var/runtime:/var/task:/var/runtime/node_modules:/node/node_modules
"$NODE_RUNTIME_PATH" --prof --logfile=/tmp/"$LAMBDA_FLAME_OUTPUT"/lambda.log nodejs/index.js

trap collect EXIT
